### ISSUE TITLE
RRect argument contained a NaN value

### ISSUE THREAD

**Issue by gcbishal** [thenifemi/flutter_polls#14]
Create Problem:

1.  Pass List of PollOption via _pollOptions_ prameter with corresponding field _votes_ set to 0
2. set _pollEnded_ parameter to **true**

Solution: resolve 0/0 = 0, not NaN

`line 252. percent: pollOption.votes / totalVotes.value`

**Comment by thenifemi** [comment]
Fixed -  https://github.com/thenifemi/flutter_polls/commit/a7fdd66b11a3a0a123b17ce84ca5936e4b450da2

**Comment by amuslimreno** [comment]
@thenifemi I still got the same Problem. I think you forgot to add the fix for line 252.

**Comment by thenifemi** [comment]
@amuslimreno Oops, I will investigate and push a fix soon.
